name: Python Environment

on:
  # To run manually
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
    
    - name: Install Python dependencies
      run: |
        python -m pip install matplotlib astropy

    - name: Hello World 
      run: |
        python -c "import astropy; print('Astropy version: '+astropy.__version__)"
        python -c "import matplotlib as mpl; print('Matplotlib version: '+mpl.__version__)"
